default: &default
  adapter: postgresql
  username: evgenia
  password: 
  host: localhost
  timeout: 5000
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
